baseURL = "https://frankie7techy.github.io/public/"
title = "z3ro :: CTF & Security Research"
theme = "PaperMod"

[params]
  description = "CTF Writeups and Security Research"
  author = "z3ro"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
